<a href="https://colab.research.google.com/github/Bharu07/Pytorch_Repository_bharu/blob/main/Intro_to_Colab_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**TENSORS**



*   A Torch. tensor is a multi-dimensional matrix containing elements of a single data type
*   Similar to Numpy Arrays, but full of fun things that make work better on GPU's(vs regular CPU's).
*   Default datatype of float 32
*   More suitable for deeplearning than a numpy array.




In [1]:
import torch
import numpy as np

In [4]:
np1 = np.random.rand(3,4)
np1

array([[0.19047193, 0.20050146, 0.81782814, 0.76985884],
       [0.9781982 , 0.47454606, 0.59358634, 0.97702113],
       [0.51796484, 0.86845971, 0.3212883 , 0.90735984]])

In [9]:
np1.dtype

dtype('float64')

In [6]:
tensor_2d = torch.randn(3,4)
tensor_2d

tensor([[ 1.0064,  0.6983,  0.8153,  1.4602],
        [-1.6446, -0.3774, -0.1488, -0.6756],
        [-0.2147, -1.7292, -0.5286, -0.5361]])

In [10]:
tensor_2d.dtype

torch.float32

In [7]:
my_tensor = torch.tensor(np1)
my_tensor

tensor([[0.1905, 0.2005, 0.8178, 0.7699],
        [0.9782, 0.4745, 0.5936, 0.9770],
        [0.5180, 0.8685, 0.3213, 0.9074]], dtype=torch.float64)