<a href="https://colab.research.google.com/github/Bharu07/Pytorch_Repository_bharu/blob/main/Tensor_math_Deep_learninig.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**TENSOR MATH OPERATION**


*   Add, Subtract, Multiply, Divide, Remainders, Exponents
*   Shorthand and uh, Longhand
*   Reassignment

In [1]:
import torch
import numpy as np

In [2]:
tensor_a = torch.tensor([1,2,3,4])
tensor_b = torch.tensor([5,6,7,8])

In [7]:
#Add
add_1 = tensor_a + tensor_b
print(add_1)

add_2 = torch.add(tensor_a,tensor_b)
print(add_2)

tensor([ 6,  8, 10, 12])
tensor([ 6,  8, 10, 12])


In [8]:
#Subtraction
sub_1 = tensor_b - tensor_a
print(sub_1)

sub_2 = torch.sub(tensor_b, tensor_a)
print(sub_2)

tensor([-4, -4, -4, -4])
tensor([-4, -4, -4, -4])


In [11]:
#Multiplication
mul_1 = tensor_a * tensor_b
print(mul_1)

mul_2 = torch.mul(tensor_a, tensor_b) # torch.mulitply also works
print(mul_2)

tensor([ 5, 12, 21, 32])
tensor([ 5, 12, 21, 32])


In [17]:
#Division
div_1 = tensor_a / tensor_b
print(div_1)

div_2 = torch.div(tensor_a, tensor_b)
print(div_2)

tensor([0.2000, 0.3333, 0.4286, 0.5000])
tensor([0.2000, 0.3333, 0.4286, 0.5000])


In [22]:
#Remainders
div_1 = tensor_b % tensor_a
print(div_1)

div_2 = torch.remainder(tensor_a, tensor_b)
print(div_2)

tensor([0, 0, 1, 0])
tensor([1, 2, 3, 4])


In [24]:
#Power
div_1 = torch.pow(tensor_a,tensor_b)
div_1

tensor([    1,    64,  2187, 65536])

In [31]:
#Another way to write longhand
tensor_a.add(tensor_b)

tensor([16, 20, 24, 28])

In [30]:
# Reassignment
#tensor_a = tensor_a + tensor_b = The left operation is same as below operation.
tensor_a.add_(tensor_b)

tensor([11, 14, 17, 20])