<a href="https://colab.research.google.com/github/Bharu07/Pytorch_Repository_bharu/blob/main/Tensor_Operations_Reshape_slice.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [5]:
import torch
my_torch = torch.arange(12)
my_torch

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [7]:
#Reshape and View
my_torch_1 = my_torch.reshape(2,6)
my_torch_1

tensor([[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11]])

In [8]:
#Reshape if we don't know the number of items using -1.
my_torch_2 = my_torch.reshape(3,-1)
my_torch_2

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

In [9]:
my_torch_3 = my_torch.reshape(-1,3)
my_torch_3

tensor([[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]])

In [11]:
my_torch_4 = my_torch.view(3,4)
my_torch_4

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

In [14]:
# Change the values.
my_torch_5 = my_torch
my_torch_5[1] = 777
my_torch_5

tensor([  0, 777,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11])

In [16]:
#Grab a specific number
specific = my_torch_5[1]
specific

tensor(777)

In [20]:
#Grab a slice
my_torch_6 = my_torch.reshape(6,-1)
my_torch_6
my_torch_6[:,1]

tensor([777,   3,   5,   7,   9,  11])

In [23]:
#Return column
my_torch_6[:,1:]

tensor([[777],
        [  3],
        [  5],
        [  7],
        [  9],
        [ 11]])